In [ ]:
print("HHH")

HHH


In [ ]:
x = 23
print(x)

23


In [ ]:
a = 2

In [ ]:
b = 1.0
print(type(b))

<class 'float'>


In [ ]:
c = 5j
d = 1 + 7j
e = complex(5, 8)

print(e, type(e))

(5+8j) <class 'complex'>


In [ ]:
jumlah = a+b
kurang = c-a
bagi = a/5
kali = a*4
pangkat = a**7
bagi_int = a//5

print (bagi_int, type(bagi_int))
print (kurang, type(kurang))

4 <class 'int'>
(-23+5j) <class 'complex'>


In [ ]:
a = float (2)
b = int(2.0)
c = complex(5)

print(a)

2.0


In [ ]:
string1 = "HHH"
contoh = 'HHH'

print(contoh)

HHH


In [ ]:
x = "Hell' World"
y = '"P"'
print(y)
print(x)

"P"
Hell' World


In [ ]:
nama = "MRT"
sapa = f"hi {nama}"
sapa2 = "halo {}".format(nama)


print(sapa2)

halo MRT


In [ ]:
karakter = "dnaidaindaudssnia"

print(len(karakter))


17


In [ ]:
print(float(int("7")))

7.0


------Tipe Array----

In [ ]:
print(a[2])
print(a[1])
print(b[-1])      #      -> urutan terakhir


5.0
2.0
0


In [ ]:
a = [1, 2.0, "5.0", 4, 5] #tipelist
b = (1, 4, 5,0) #tipetuple -> tidak bisa diubah
                #           ->  bisa tidak pakai kurung
c = {4, 6, 7, 7} #tipeset -> tidak memungkinkan nilai sama berulang (teori himpunan)



In [ ]:
print(a[0:4])
print(a[:3])
print(a[1:])

[1, 2.0, '5.0', 4]
[1, 2.0, '5.0']
[2.0, '5.0', 4, 5]


In [ ]:
print(a[0::2])     # titik dua setelah urutan artinya mulai berapa kali
print(a[0:4:2])    #format [mulaitulis : mulaiberhenti : step]

[1, '5.0', 5]
[1, '5.0']


In [ ]:
a = [1, 2, 3, 4, 5, 6]
a[1] = 10
print(a)

[1, 10, 3, 4, 5, 6]


In [ ]:
a = {"nama" : "MRT", "Status" : "Kabur"} #"Key" : "Value", untuk memanggil ditulis "Key"

print(a["nama"])
a["nama"] = "Dobleh"
print(a)

MRT
{'nama': 'Dobleh', 'Status': 'Kabur'}


In [ ]:
a = [1,2,3,4]
a.append(5)
a.insert(1, 15)     #(setelah, isi)
print(a)

[1, 15, 2, 3, 4, 5]


In [ ]:
a = [1,2,3,4]
b = a.copy()
b[1] = 9
print(a)
print(b)


[1, 2, 3, 4]
[1, 9, 3, 4]


In [ ]:
a = True
b = False
# Operator : <, >, <=, >=,==,!=
# Operator dlm simbol : and (&), or (|), not (~)

c = ((6<7 and 6==7)) or ((False and (2!=2)))
print(c)


False


In [ ]:
Nilai = 6

if Nilai> 3:
  print("Nilai lebih dari 3")
elif Nilai<3 :
  print("Nilai kurang dari 3")
else:
  print("Nilai = 3")

Nilai lebih dari 3


In [ ]:
a = [1]
b = [1,2,3,4,5,6]

if a:
  print("YA")
  if True:
    print("A")
if 1:
  print("YA JUGA")
if 2 in b:
  print("ada")

a = None

if a is None:
  print("None")
if a is not None:
  print("Uduk None")


YA
A
YA JUGA
ada
None


In [ ]:
a = 1
while a<7:
  a +=1
  print(a)


2
3
4
5
6
7


In [ ]:
a = 0   #digunakan saat tidak tau kapan terpenuhi, tetapi berhenti saat terpenuhi
while True:
  print(a)
  a += 1
  if a > 5:
    break

0
1
2
3
4
5


In [ ]:
for i in range(5):
  print(i)

0
1
2
3
4


In [ ]:
a = [1,2,3,4]

for i in a:
  print(i)

1
2
3
4


In [ ]:
a = [1,2,3,4]

for i in a:
  print(i)
  print(i)

1
1
2
2
3
3
4
4


In [ ]:
a = {"Nama" : "Dobleh", "Status" : "Kabur"}

for i in a:
  print(i)

  


Nama
Status


In [ ]:
a = {"Nama" : "Dobleh", "Status" : "Kabur"}

for i in a:
  print(a[i])

Dobleh
Kabur


In [ ]:
for i in a.items():
  print(i)

('Nama', 'Dobleh')
('Status', 'Kabur')


In [ ]:
for i in range(1, 10, 1):
  print(i)
  if i<9:
    break


1


In [ ]:
a = [i for i in range(10)]

key = ["Nama", "Umur"]
value = ["Wahyu", 20]

b = { key[i] : value [i] for i in range(len(key))}
c = dict(zip(key, value))

print(a)
print(b)
print(c)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
{'Nama': 'Wahyu', 'Umur': 20}
{'Nama': 'Wahyu', 'Umur': 20}


In [ ]:
a = [1,2,3,4]
b = set(a)
c = tuple(a)

print(b)
print(c)

{1, 2, 3, 4}
(1, 2, 3, 4)


In [ ]:
nama = input("Namamu ? ")
umur = input("Umurmu ? ")
print("Hai " + nama + "nub" + " , Umurmu " + umur + " , Dasar Tuek")

Namamu ? Rev
Umurmu ? 18
Hai Revnub , Umurmu 18 , Dasar Tuek


In [ ]:
c = 6                   #global variable = diluar fungsi, local variable = dalam fungsi
def operation(a, b):    #tanda fungsi yaitu def
  hasil = a+b+c
  return hasil

print(operation(5, 8))

19


In [ ]:
c = 6                   
def operation(a, b, d = 7)
  hasil = a+b+c+d
  return hasil

print(operation(5, 8, 3))

22


In [ ]:
def operation2(a, b):
  penjumlahan = a + b
  pengurangan = a - b
  return penjumlahan, pengurangan

print(operation2(3, 4))

(7, -1)


In [ ]:
def operation2(a, b):
  penjumlahan = a + b
  pengurangan = a - b


print(operation2(3, 4))

None


LIBRARY NUMPY




In [ ]:
import numpy as np

In [ ]:
a = [1,2,3,4,5,6]
b = [6,5,4,3,2,1]
a+b

[1, 2, 3, 4, 5, 6, 6, 5, 4, 3, 2, 1]

In [ ]:
h1 = np.array(a)
h2 = np.array(b)

print(h1+h2)
print(h1-h2)
print(h1**h2)
print(h1*h2)
print(h1/h2)
print(h1//h2)

[7 7 7 7 7 7]
[-5 -3 -1  1  3  5]
[ 1 32 81 64 25  6]
[ 6 10 12 12 10  6]
[0.16666667 0.4        0.75       1.33333333 2.5        6.        ]
[0 0 0 1 2 6]


In [ ]:
a = list(range(1000))

In [ ]:
%timeit sum(a)

100000 loops, best of 3: 4 µs per loop


In [ ]:
b = np.array(a)

%timeit np.sum(b)

The slowest run took 255.95 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 5.12 µs per loop


In [ ]:
b.shape

(1000,)

In [ ]:
b.dtype        #tipe data

dtype('int64')

In [ ]:
a = [1,2,3,4,-5]
b = np.array(a, np.uint8)     #diakhir 2 pangkat 8 dikurang angka terakhir 
print(b)

[  1   2   3   4 251]


In [ ]:
b = b.astype(np.float32)      #mengganti tipe data
print(b)

[  1.   2.   3.   4. 251.]


In [ ]:
b = np.arange(3, 8, 0.5)   #np.arrange(nilai awal, nilai akhir, kenaikan)
c = np.linspace(0, 10, 8)  #np.linspace(nilai awal, nilai akhir, jumlah data)
print(b)
print(c)

[3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5]
[ 0.          1.42857143  2.85714286  4.28571429  5.71428571  7.14285714
  8.57142857 10.        ]


In [ ]:
print(c)
print(c[0:7:5])     # dari nilai 0 sampe 7 dengan kenaikan 5

[ 0.          1.42857143  2.85714286  4.28571429  5.71428571  7.14285714
  8.57142857 10.        ]
[0.         7.14285714]


In [ ]:
print(c)
print(c[[1, -1]])  #ngambil nilai ke 1 dan terakhir

[ 0.          1.42857143  2.85714286  4.28571429  5.71428571  7.14285714
  8.57142857 10.        ]
[ 1.42857143 10.        ]


In [ ]:
print(c)
index = [0, 1, -2]   #ngambil nilai tertentu secara acak
print(c[index])

[ 0.          1.42857143  2.85714286  4.28571429  5.71428571  7.14285714
  8.57142857 10.        ]
[0.         1.42857143 8.57142857]


In [ ]:
print(c)
mask = c < 2       #menentukan nilai T/F
print(mask)

[ 0.          1.42857143  2.85714286  4.28571429  5.71428571  7.14285714
  8.57142857 10.        ]
[ True  True False False False False False False]


In [ ]:
print(c)
mask = c < 2
print(mask)

c[mask] #menunjukkan nilai yang true

[ 0.          1.42857143  2.85714286  4.28571429  5.71428571  7.14285714
  8.57142857 10.        ]
[ True  True False False False False False False]


array([0.        , 1.42857143])

In [ ]:
c[c < 6]  #antara

array([0.        , 1.42857143, 2.85714286, 4.28571429, 5.71428571])

In [ ]:
c[(c<6) * (c>1)]     #and/dan setara dengan tanda *, or/atau setara tanda +

array([1.42857143, 2.85714286, 4.28571429, 5.71428571])

ARRAY 2D

In [ ]:
a = [[1,2,3,4], [4,3,2,1]]
print(a)

[[1, 2, 3, 4], [4, 3, 2, 1]]


In [ ]:
b = np.array(a)
print(b)

[[1 2 3 4]
 [4 3 2 1]]


In [ ]:
c = np.arange(36)   #list dari 0 sampe 35 (36tidak termasuk)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


In [ ]:
d = c.reshape(6,6)
print(d)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [ ]:
print(d.shape)

(6, 6)


In [ ]:
contoh = np.arange(2,18).reshape(4,4)
print(contoh)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]


In [ ]:
contoh = np.arange(2,18).reshape((4,4)).astype(np.float)
print(contoh)

[[ 2.  3.  4.  5.]
 [ 6.  7.  8.  9.]
 [10. 11. 12. 13.]
 [14. 15. 16. 17.]]


In [ ]:
print(contoh[2, 2])   #[baris, kolom]

12


In [ ]:
print(contoh[0])
print(contoh[:, 1])
print(contoh[2:, 2])
print(contoh[3:, :2])

[2 3 4 5]
[ 3  7 11 15]
[12 16]
[[14 15]]


In [ ]:
print(contoh[2:, 2:])
print(contoh[1:3:2, 0:3:2])

[[12 13]
 [16 17]]
[[6 8]]


In [ ]:

baris = [0,3]
kolom = [1,2]
print(contoh[baris, kolom])

[ 3 16]


In [ ]:
#Latihan

x = np.arange(25).reshape(5,5)
print(x)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
#MERAH

print(x[:, 1:4:2])

[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]
 [21 23]]


In [ ]:
#ABU

kolom = [0,2, 4]
print(x[:5, kolom])

[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]
 [20 22 24]]


In [ ]:
#KUNING

print(x[4:, :5])

[[20 21 22 23 24]]


In [ ]:
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
#BIRU

print(x[1:4:2, 0:3:2])   #atau
print(x[[1,1,3,3], [0,2,0,2]])

[[ 5  7]
 [15 17]]
[ 5  7 15 17]


In [ ]:
song = np.zeros((6,6))
print(song)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
satu = np.ones((6,6))
print(satu)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:
acak = np.random.random((4,4))
print(acak)

[[0.53611281 0.43084743 0.37613724 0.13458906]
 [0.89276087 0.96020173 0.74660413 0.16721521]
 [0.18612431 0.83241138 0.6447217  0.35597367]
 [0.09923502 0.70567512 0.01497046 0.26271609]]


In [ ]:
test = np.random.randint(10, 100, (4,4))
print(test)

[[46 62 28 97]
 [87 25 75 33]
 [42 50 16 67]
 [24 45 45 27]]


In [ ]:
nilai = test < 50
nilai = test[nilai] #Masking / menunjukkan nilai yg memenuhi (<50)
print(nilai)

[46 28 25 33 42 16 24 45 45 27]


In [ ]:
np.where(test < 20)   #Letak yang kurang dari 20

(array([2]), array([2]))

In [ ]:
np.max(test) #menunjukkan nilai maksimal


97

In [ ]:
np.argmax(test) #menunjukkan nilai maksimal dlm urutan

3

In [ ]:
np.where(test == np.max(test)) #menunjukkan letak nilai maksimal dalam bentuk posisi matriks

(array([0]), array([3]))

In [ ]:
print(np.max(test, axis = 0)) #Nilai maksimal tiap kolom

[87 62 75 97]


In [ ]:
print(np.max(test, axis = 1)) #Nilai maksimal tiap baris

[97 87 67 45]


In [ ]:
print(np.min(test, axis = 0)) #Nilai minimal tiap kolom

[24 25 16 27]


In [ ]:
print(np.min(test, axis = 1)) #Nilai minimal tiap baris

[28 25 16 24]


In [ ]:
print(np.argmin(test, axis = 0)) #Letak nilai minimum tiap kolom

[3 1 2 3]


In [ ]:
print(np.argmin(test, axis = 1)) #Letak nilai maksimum tiap kolom

[2 1 2 0]
